In [1]:
# import modules
import pandas as pd
import numpy as np
import requests
import urllib.request, urllib.parse, urllib.error
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re
from datetime import datetime
from ratelimit import limits
from time import time, sleep
from random import randint
import matplotlib.pyplot as plt
%matplotlib inline
from warnings import warn

In [2]:
df1 = pd.read_csv('league_raw_data.csv')
df2 = pd.read_csv('league_raw_data_pt2.csv')

In [3]:
combined_data = pd.concat([df1, df2])

In [4]:
combined_data.to_csv('league_data.csv', index=False)

In [5]:
league_data = pd.read_csv('league_data.csv')

In [6]:
s = pd.Series(league_data.index // 5)
df = league_data[s.groupby(s).transform('count') == 5]

In [7]:
league_team_data = league_data.groupby(df.index // 5).agg({'gameId':'last','gameDuration':'last','gameVersion':'last',
                                        'teamId': 'last','win':'last','firstBlood':'last',
                                        'firstTower':'last','firstInhibitor':'last',
                                        'firstBaron':'last','firstDragon':'last',
                                        'firstRiftHerald':'last','towerKills':'last', 
                                        'inhibitorKills':'last', 'baronKills':'last', 
                                        'dragonKills':'last','riftHeraldKills':'last',
                                        'kills':'sum', 'deaths':'sum', 'assists':'sum',
                                        'totalDamageDealtToChampions':'sum', 'visionScore':'sum',
                                        'goldEarned':'sum', 'champLevel':'mean',
                                        'totalMinionsKilled':'sum'})

In [8]:
league_team_data.rename(columns = {'champLevel':'averageChampLevel'}, inplace = True)
league_team_data['gameDuration'] = league_team_data.gameDuration.astype(int)
league_team_data.rename(columns = {'gameDuration':'gameDuration(seconds)'}, inplace = True)

In [9]:
league_team_data.to_csv('league_team_data.csv', index=False)

In [15]:
league_team_data

,gameId,gameDuration(seconds),gameVersion,teamId,win,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,dragonKills,riftHeraldKills,kills,deaths,assists,totalDamageDealtToChampions,visionScore,goldEarned,averageChampLevel,totalMinionsKilled
0,3380752332,1425,10.8.317.3760,100,Win,True,True,True,True,True,...,4,2,26,7,49,60502,97,51396,13.4,586
1,3380752332,1425,10.8.317.3760,200,Fail,False,False,False,False,False,...,0,0,7,26,15,33115,106,34647,11.2,474
2,3380718178,915,10.8.317.3760,100,Fail,False,False,False,False,False,...,0,1,6,17,14,25786,64,25552,9.0,361
3,3380718178,915,10.8.317.3760,200,Win,True,False,False,False,True,...,2,0,17,6,20,30792,67,28068,9.4,324
4,3380672585,1189,10.8.317.3760,100,Win,True,True,False,False,False,...,1,1,26,12,35,47356,107,41914,11.8,503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31273,3333123950,1329,10.6.313.8894,200,Fail,False,False,False,False,True,...,1,0,17,36,26,45682,119,40366,11.2,489
31274,3333058113,2104,10.6.313.8894,100,Win,False,True,False,False,False,...,3,1,33,33,62,121369,167,68732,16.8,781
31275,3333058113,2104,10.6.313.8894,200,Fail,True,False,True,True,True,...,2,1,33,33,65,124156,189,68457,16.2,747
31276,3332433241,1370,10.6.313.8894,100,Win,True,True,True,True,False,...,1,2,34,14,63,82909,133,52991,13.4,548
31277,3332433241,1370,10.6.313.8894,200,Fail,False,False,False,False,True,...,1,0,14,34,22,47680,105,34816,11.4,471